/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository of this plugin.
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ArticleOptimizerPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_PROMPTS = [
  {
    id: "preset-format",
    name: "\u683C\u5F0F\u4F18\u5316",
    content: "\u4F60\u662F\u4E00\u4F4D\u4E13\u4E1A\u7684\u6587\u7AE0\u7F16\u8F91\u3002\u8BF7\u4F18\u5316\u4EE5\u4E0B\u6587\u7AE0\u7684\u6392\u7248\u4E0E\u683C\u5F0F\uFF0C\u9075\u5B88\u4EE5\u4E0B\u89C4\u5219\uFF1A\n1. \u7981\u6B62\u4F7F\u7528 H1\uFF08# \u4E00\u7EA7\u6807\u9898\uFF09\uFF0C\u6700\u5927\u6807\u9898\u5C42\u7EA7\u4E3A H2\uFF08## \u4E8C\u7EA7\u6807\u9898\uFF09\uFF0C\u5C42\u7EA7\u5206\u660E\uFF1B\n2. \u6587\u7AE0\u6700\u524D\u9762\u4FDD\u7559\u6216\u8865\u5145\u4E00\u6BB5\u5F15\u8A00/\u8BF4\u660E\u6587\u5B57\uFF0C\u7136\u540E\u518D\u8FDB\u5165\u6807\u9898\u7ED3\u6784\uFF1B\n3. \u6807\u9898\u4F7F\u7528\u5E73\u884C\u5E76\u5217\u7684\u5F62\u5F0F\uFF08\u5982\uFF1A## \u80CC\u666F\u3001## \u65B9\u6848\u3001## \u603B\u7ED3\uFF09\uFF0C\u4E0D\u8981\u4F7F\u7528\u300C\u4E00\u3001\u4E8C\u3001\u4E09\u300D\u6216\u300C\u7B2C\u4E00\u6B65\u3001\u7B2C\u4E8C\u6B65\u300D\u7B49\u6B65\u9AA4\u5F0F\u7F16\u53F7\uFF1B\n4. \u4F18\u5316\u5B8C\u6210\u540E\u76F4\u63A5\u8F93\u51FA\u4F18\u5316\u540E\u7684\u6587\u7AE0\u5185\u5BB9\uFF0C\u4E0D\u8981\u5728\u7ED3\u5C3E\u6DFB\u52A0\u4EFB\u4F55\u8BF4\u660E\u6027\u6587\u5B57\uFF08\u5982\u300C\u4EE5\u4E0A\u4E3A\u683C\u5F0F\u4F18\u5316\u7ED3\u679C\u300D\u7B49\uFF09\uFF1B\n5. \u53EA\u4F18\u5316\u683C\u5F0F\u548C\u7ED3\u6784\uFF0C\u4E0D\u6539\u53D8\u539F\u6587\u7684\u6838\u5FC3\u5185\u5BB9\u548C\u610F\u601D\uFF0C\u4E0D\u5927\u5E45\u6539\u5199\u3002",
    isDefault: true,
    createdAt: Date.now()
  },
  {
    id: "preset-seo",
    name: "SEO \u4F18\u5316",
    content: "\u4F60\u662F\u4E00\u4F4DSEO\u4E13\u5BB6\u3002\u8BF7\u4F18\u5316\u4EE5\u4E0B\u6587\u7AE0\u7684\u641C\u7D22\u5F15\u64CE\u53EF\u89C1\u6027\uFF0C\u5305\u62EC\uFF1A\u4F18\u5316\u6807\u9898\u4F7F\u5176\u66F4\u5438\u5F15\u70B9\u51FB\u3001\u8C03\u6574\u5173\u952E\u8BCD\u5BC6\u5EA6\u548C\u5206\u5E03\u3001\u6DFB\u52A0\u9002\u5F53\u7684H\u6807\u7B7E\u7ED3\u6784\u3001\u4F18\u5316\u9996\u6BB5\u548C\u672B\u6BB5\u3002\u8981\u6C42\uFF1A\u53EA\u505ASEO\u76F8\u5173\u7684\u4F18\u5316\uFF0C\u4FDD\u6301\u539F\u6587\u6838\u5FC3\u5185\u5BB9\u4E0D\u53D8\uFF0C\u4E0D\u5927\u5E45\u6539\u5199\u3002",
    isDefault: false,
    createdAt: Date.now()
  },
  {
    id: "preset-geo",
    name: "GEO \u4F18\u5316",
    content: "\u4F60\u662F\u4E00\u4F4DGEO\uFF08Generative Engine Optimization\uFF09\u4E13\u5BB6\u3002\u8BF7\u4F18\u5316\u4EE5\u4E0B\u6587\u7AE0\uFF0C\u4F7F\u5176\u66F4\u5BB9\u6613\u88ABAI\u641C\u7D22\u5F15\u64CE\u5F15\u7528\u548C\u63A8\u8350\uFF0C\u5305\u62EC\uFF1A\u589E\u52A0\u7ED3\u6784\u5316\u6570\u636E\u63CF\u8FF0\u3001\u4F18\u5316\u5185\u5BB9\u4F7F\u5176\u66F4\u6613\u88ABAI\u7406\u89E3\u548C\u5F15\u7528\u3001\u786E\u4FDD\u5173\u952E\u4FE1\u606F\u6E05\u6670\u660E\u786E\u3002\u8981\u6C42\uFF1A\u53EA\u505AGEO\u76F8\u5173\u7684\u4F18\u5316\uFF0C\u4FDD\u6301\u539F\u6587\u6838\u5FC3\u5185\u5BB9\u4E0D\u53D8\uFF0C\u4E0D\u5927\u5E45\u6539\u5199\u3002",
    isDefault: false,
    createdAt: Date.now()
  },
  {
    id: "preset-polish",
    name: "\u6DA6\u8272\u7CBE\u7B80",
    content: "\u4F60\u662F\u4E00\u4F4D\u8D44\u6DF1\u7684\u6587\u5B57\u7F16\u8F91\u3002\u8BF7\u5BF9\u4EE5\u4E0B\u6587\u7AE0\u8FDB\u884C\u6DA6\u8272\u548C\u7CBE\u7B80\uFF1A\u53BB\u9664\u5197\u4F59\u8868\u8FF0\u3001\u4FEE\u6B63\u8BED\u6CD5\u9519\u8BEF\u3001\u4F18\u5316\u53E5\u5B50\u7ED3\u6784\u3001\u4F7F\u8868\u8FBE\u66F4\u52A0\u7CBE\u70BC\u51C6\u786E\u3002\u8981\u6C42\uFF1A\u4FDD\u6301\u539F\u6587\u6838\u5FC3\u610F\u601D\u548C\u98CE\u683C\u4E0D\u53D8\uFF0C\u53EA\u505A\u6DA6\u8272\u7CBE\u7B80\uFF0C\u4E0D\u6539\u53D8\u5185\u5BB9\u65B9\u5411\u3002",
    isDefault: false,
    createdAt: Date.now()
  },
  {
    id: "preset-structure",
    name: "\u7ED3\u6784\u4F18\u5316",
    content: "\u4F60\u662F\u4E00\u4F4D\u6587\u7AE0\u7ED3\u6784\u4F18\u5316\u4E13\u5BB6\u3002\u8BF7\u4F18\u5316\u4EE5\u4E0B\u6587\u7AE0\u7684\u7ED3\u6784\uFF0C\u9075\u5B88\u4EE5\u4E0B\u89C4\u5219\uFF1A\n1. \u7981\u6B62\u4F7F\u7528 H1\uFF08# \u4E00\u7EA7\u6807\u9898\uFF09\uFF0C\u6700\u5927\u6807\u9898\u5C42\u7EA7\u4E3A H2\uFF08## \u4E8C\u7EA7\u6807\u9898\uFF09\uFF1B\n2. \u6587\u7AE0\u6700\u524D\u9762\u4FDD\u7559\u6216\u8865\u5145\u4E00\u6BB5\u5F15\u8A00/\u8BF4\u660E\u6587\u5B57\uFF0C\u7136\u540E\u518D\u8FDB\u5165\u6807\u9898\u7ED3\u6784\uFF1B\n3. \u6807\u9898\u4F7F\u7528\u5E73\u884C\u5E76\u5217\u7684\u5F62\u5F0F\uFF0C\u4E0D\u8981\u4F7F\u7528\u300C\u4E00\u3001\u4E8C\u3001\u4E09\u300D\u6216\u6B65\u9AA4\u5F0F\u7F16\u53F7\uFF1B\n4. \u4F18\u5316\u5B8C\u6210\u540E\u76F4\u63A5\u8F93\u51FA\u4F18\u5316\u540E\u7684\u6587\u7AE0\u5185\u5BB9\uFF0C\u4E0D\u8981\u5728\u7ED3\u5C3E\u6DFB\u52A0\u4EFB\u4F55\u8BF4\u660E\u6027\u6587\u5B57\uFF1B\n5. \u53EA\u8C03\u6574\u6587\u7AE0\u7ED3\u6784\u548C\u6BB5\u843D\u903B\u8F91\uFF0C\u4E0D\u6539\u53D8\u5404\u90E8\u5206\u7684\u6838\u5FC3\u5185\u5BB9\uFF0C\u4FDD\u6301\u539F\u6587\u610F\u601D\u4E0D\u53D8\u3002",
    isDefault: false,
    createdAt: Date.now()
  }
];
var DEFAULT_SETTINGS = {
  apiEndpoint: "http://localhost:11434/v1/chat/completions",
  apiKey: "",
  modelName: "llama3",
  prompts: DEFAULT_PROMPTS,
  defaultPromptId: "preset-format",
  autoBackup: true,
  showDiffSummary: true,
  optimizeShortcut: "ctrl+shift+o"
};
var OptimizerSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "AI \u914D\u7F6E" });
    new import_obsidian.Setting(containerEl).setName("API \u5730\u5740").setDesc("OpenAI \u517C\u5BB9\u7684 Chat Completions \u63A5\u53E3\u5730\u5740").addText(
      (text) => text.setPlaceholder("http://localhost:11434/v1/chat/completions").setValue(this.plugin.settings.apiEndpoint).onChange(async (value) => {
        this.plugin.settings.apiEndpoint = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("API Key").setDesc("\u7559\u7A7A\u5219\u4E0D\u53D1\u9001\uFF08Ollama \u672C\u5730\u65E0\u9700\u586B\u5199\uFF09").addText(
      (text) => text.setPlaceholder("sk-...").setValue(this.plugin.settings.apiKey).onChange(async (value) => {
        this.plugin.settings.apiKey = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u6A21\u578B\u540D\u79F0").setDesc("\u5982 llama3\u3001qwen2\u3001gpt-4 \u7B49").addText(
      (text) => text.setPlaceholder("llama3").setValue(this.plugin.settings.modelName).onChange(async (value) => {
        this.plugin.settings.modelName = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h2", { text: "\u7F16\u8F91\u5668\u884C\u4E3A" });
    new import_obsidian.Setting(containerEl).setName("\u81EA\u52A8\u5907\u4EFD\u539F\u6587").setDesc("\u4F18\u5316\u524D\u81EA\u52A8\u5C06\u539F\u6587\u590D\u5236\u5230\u526A\u8D34\u677F").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoBackup).onChange(async (value) => {
        this.plugin.settings.autoBackup = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u663E\u793A\u5DEE\u5F02\u6458\u8981").setDesc("\u4F18\u5316\u540E\u663E\u793A\u53D8\u5316\u7EDF\u8BA1").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showDiffSummary).onChange(async (value) => {
        this.plugin.settings.showDiffSummary = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h2", { text: "\u63D0\u793A\u8BCD\u5E93" });
    this.renderPromptList(containerEl);
  }
  renderPromptList(containerEl) {
    const listEl = containerEl.createDiv({ cls: "optimizer-prompt-list" });
    listEl.empty();
    for (const prompt of this.plugin.settings.prompts) {
      const itemEl = listEl.createDiv({ cls: "optimizer-prompt-item" });
      const headerEl = itemEl.createDiv({
        cls: "optimizer-prompt-header"
      });
      headerEl.createSpan({
        cls: "optimizer-prompt-name",
        text: prompt.name + (prompt.isDefault ? " \u2B50\u9ED8\u8BA4" : "")
      });
      const btnGroup = headerEl.createDiv({ cls: "optimizer-prompt-btns" });
      if (!prompt.isDefault) {
        btnGroup.createEl("button", {
          text: "\u8BBE\u4E3A\u9ED8\u8BA4",
          cls: "mod-cta optimizer-btn-sm"
        }).onclick = async () => {
          this.plugin.settings.prompts.forEach((p) => p.isDefault = false);
          prompt.isDefault = true;
          this.plugin.settings.defaultPromptId = prompt.id;
          await this.plugin.saveSettings();
          this.renderPromptList(containerEl);
        };
      }
      if (!prompt.id.startsWith("preset-")) {
        btnGroup.createEl("button", {
          text: "\u5220\u9664",
          cls: "mod-warning optimizer-btn-sm"
        }).onclick = async () => {
          var _a;
          this.plugin.settings.prompts = this.plugin.settings.prompts.filter(
            (p) => p.id !== prompt.id
          );
          if (this.plugin.settings.defaultPromptId === prompt.id) {
            this.plugin.settings.defaultPromptId = ((_a = this.plugin.settings.prompts[0]) == null ? void 0 : _a.id) || "";
            if (this.plugin.settings.prompts[0]) {
              this.plugin.settings.prompts[0].isDefault = true;
            }
          }
          await this.plugin.saveSettings();
          this.renderPromptList(containerEl);
        };
      }
      const contentEl = itemEl.createDiv({ cls: "optimizer-prompt-content" });
      const textarea = contentEl.createEl("textarea", {
        cls: "optimizer-prompt-textarea"
      });
      textarea.value = prompt.content;
      textarea.rows = 3;
      textarea.onchange = async () => {
        prompt.content = textarea.value;
        await this.plugin.saveSettings();
      };
    }
    new import_obsidian.Setting(listEl).setName("\u6DFB\u52A0\u65B0\u63D0\u793A\u8BCD").setDesc("\u8F93\u5165\u63D0\u793A\u8BCD\u540D\u79F0\u540E\u70B9\u51FB\u6DFB\u52A0").addText((text) => {
      text.setPlaceholder("\u63D0\u793A\u8BCD\u540D\u79F0");
      text.inputEl.className = "optimizer-new-prompt-name";
    }).addButton(
      (btn) => btn.setButtonText("\u6DFB\u52A0").setClass("mod-cta").onClick(async () => {
        var _a;
        const nameInput = listEl.querySelector(
          ".optimizer-new-prompt-name"
        );
        const name = (_a = nameInput == null ? void 0 : nameInput.value) == null ? void 0 : _a.trim();
        if (!name) return;
        const newPrompt = {
          id: "custom-" + Date.now(),
          name,
          content: "",
          isDefault: false,
          createdAt: Date.now()
        };
        this.plugin.settings.prompts.push(newPrompt);
        await this.plugin.saveSettings();
        this.renderPromptList(containerEl);
      })
    );
  }
};

// src/ai-service.ts
var import_obsidian2 = require("obsidian");
var AIService = class {
  constructor(settings) {
    this.settings = settings;
  }
  updateSettings(settings) {
    this.settings = settings;
  }
  /**
   * 非流式请求
   */
  async chat(messages) {
    var _a, _b, _c;
    const headers = {
      "Content-Type": "application/json"
    };
    if (this.settings.apiKey) {
      headers["Authorization"] = `Bearer ${this.settings.apiKey}`;
    }
    const body = {
      model: this.settings.modelName,
      messages,
      stream: false
    };
    try {
      const response = await (0, import_obsidian2.requestUrl)({
        url: this.settings.apiEndpoint,
        method: "POST",
        headers,
        body: JSON.stringify(body)
      });
      const data = response.json;
      if ((_c = (_b = (_a = data == null ? void 0 : data.choices) == null ? void 0 : _a[0]) == null ? void 0 : _b.message) == null ? void 0 : _c.content) {
        return data.choices[0].message.content;
      }
      throw new Error("API \u8FD4\u56DE\u683C\u5F0F\u5F02\u5E38: " + JSON.stringify(data));
    } catch (err) {
      const msg = (err == null ? void 0 : err.message) || String(err);
      new import_obsidian2.Notice("AI \u8BF7\u6C42\u5931\u8D25: " + msg, 5e3);
      throw err;
    }
  }
  /**
   * 流式请求（SSE）
   */
  async chatStream(messages, callbacks) {
    var _a, _b, _c, _d;
    const headers = {
      "Content-Type": "application/json",
      Accept: "text/event-stream"
    };
    if (this.settings.apiKey) {
      headers["Authorization"] = `Bearer ${this.settings.apiKey}`;
    }
    const body = {
      model: this.settings.modelName,
      messages,
      stream: true
    };
    let fullText = "";
    try {
      const response = await fetch(this.settings.apiEndpoint, {
        method: "POST",
        headers,
        body: JSON.stringify(body)
      });
      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`HTTP ${response.status}: ${errorText}`);
      }
      const reader = (_a = response.body) == null ? void 0 : _a.getReader();
      if (!reader) {
        throw new Error("\u65E0\u6CD5\u83B7\u53D6\u54CD\u5E94\u6D41");
      }
      const decoder = new TextDecoder();
      let buffer = "";
      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        buffer += decoder.decode(value, { stream: true });
        const lines = buffer.split("\n");
        buffer = lines.pop() || "";
        for (const line of lines) {
          const trimmed = line.trim();
          if (!trimmed || !trimmed.startsWith("data: ")) continue;
          const data = trimmed.slice(6);
          if (data === "[DONE]") {
            callbacks.onDone(fullText);
            return;
          }
          try {
            const parsed = JSON.parse(data);
            const delta = (_d = (_c = (_b = parsed == null ? void 0 : parsed.choices) == null ? void 0 : _b[0]) == null ? void 0 : _c.delta) == null ? void 0 : _d.content;
            if (delta) {
              fullText += delta;
              callbacks.onChunk(fullText);
            }
          } catch (e) {
          }
        }
      }
      callbacks.onDone(fullText);
    } catch (err) {
      const msg = (err == null ? void 0 : err.message) || String(err);
      callbacks.onError(err);
      new import_obsidian2.Notice("AI \u6D41\u5F0F\u8BF7\u6C42\u5931\u8D25: " + msg, 5e3);
    }
  }
};

// src/optimizer.ts
var import_obsidian3 = require("obsidian");
var Optimizer = class {
  constructor(settings, aiService) {
    this.settings = settings;
    this.isOptimizing = false;
    this.aiService = aiService;
  }
  updateSettings(settings) {
    this.settings = settings;
    this.aiService.updateSettings(settings);
  }
  get optimizing() {
    return this.isOptimizing;
  }
  /**
   * 获取默认提示词
   */
  getDefaultPrompt() {
    return this.settings.prompts.find(
      (p) => p.id === this.settings.defaultPromptId
    );
  }
  /**
   * 根据 ID 获取提示词
   */
  getPromptById(id) {
    return this.settings.prompts.find((p) => p.id === id);
  }
  /**
   * 执行优化（核心入口）
   */
  async optimize(editor, view, promptId) {
    var _a;
    if (this.isOptimizing) {
      new import_obsidian3.Notice("\u6B63\u5728\u4F18\u5316\u4E2D\uFF0C\u8BF7\u7A0D\u5019...");
      return;
    }
    const prompt = promptId ? this.getPromptById(promptId) : this.getDefaultPrompt();
    if (!prompt) {
      new import_obsidian3.Notice("\u672A\u627E\u5230\u63D0\u793A\u8BCD\uFF0C\u8BF7\u5148\u5728\u8BBE\u7F6E\u4E2D\u914D\u7F6E");
      return;
    }
    const selectedText = editor.getSelection();
    const isSelection = selectedText.length > 0;
    const content = isSelection ? selectedText : editor.getValue();
    if (!content.trim()) {
      new import_obsidian3.Notice("\u6587\u7AE0\u5185\u5BB9\u4E3A\u7A7A\uFF0C\u65E0\u9700\u4F18\u5316");
      return;
    }
    if (this.settings.autoBackup) {
      try {
        await navigator.clipboard.writeText(content);
      } catch (e) {
      }
    }
    this.isOptimizing = true;
    const statusBar = (_a = view.app.workspace.plugin) == null ? void 0 : _a.statusBarItem;
    const statusText = "\u{1F504} AI \u4F18\u5316\u4E2D...";
    new import_obsidian3.Notice(statusText);
    const messages = [
      { role: "system", content: prompt.content },
      { role: "user", content }
    ];
    try {
      if (isSelection) {
        await this.optimizeSelection(editor, messages);
      } else {
        await this.optimizeFullDoc(editor, messages);
      }
    } catch (err) {
    } finally {
      this.isOptimizing = false;
    }
  }
  /**
   * 优化选中文本（流式替换）
   */
  async optimizeSelection(editor, messages) {
    const from = editor.getCursor("from");
    const to = editor.getCursor("to");
    const originalText = editor.getSelection();
    let lastText = "";
    editor.replaceSelection("");
    await this.aiService.chatStream(messages, {
      onChunk: (fullText) => {
        const delta = fullText.slice(lastText.length);
        lastText = fullText;
        editor.replaceRange(delta, editor.getCursor("from"));
      },
      onDone: (fullText) => {
        if (this.settings.showDiffSummary) {
          this.showDiffSummary(originalText, fullText);
        }
        new import_obsidian3.Notice("\u2705 \u4F18\u5316\u5B8C\u6210");
      },
      onError: (err) => {
        const currentFrom = editor.getCursor("from");
        const currentTo = {
          line: currentFrom.line,
          ch: currentFrom.ch + lastText.length
        };
        editor.replaceRange(originalText, currentFrom, currentTo);
        new import_obsidian3.Notice("\u274C \u4F18\u5316\u5931\u8D25\uFF0C\u5DF2\u6062\u590D\u539F\u6587");
      }
    });
  }
  /**
   * 优化全文（流式替换）
   */
  async optimizeFullDoc(editor, messages) {
    const originalText = editor.getValue();
    let lastText = "";
    editor.setValue("");
    await this.aiService.chatStream(messages, {
      onChunk: (fullText) => {
        const delta = fullText.slice(lastText.length);
        lastText = fullText;
        const lastLine = editor.lastLine();
        const lastCh = editor.getLine(lastLine).length;
        editor.replaceRange(delta, { line: lastLine, ch: lastCh });
      },
      onDone: (fullText) => {
        if (this.settings.showDiffSummary) {
          this.showDiffSummary(originalText, fullText);
        }
        new import_obsidian3.Notice("\u2705 \u4F18\u5316\u5B8C\u6210");
      },
      onError: (err) => {
        editor.setValue(originalText);
        new import_obsidian3.Notice("\u274C \u4F18\u5316\u5931\u8D25\uFF0C\u5DF2\u6062\u590D\u539F\u6587");
      }
    });
  }
  /**
   * 显示差异摘要
   */
  showDiffSummary(original, optimized) {
    const origLines = original.split("\n").length;
    const optLines = optimized.split("\n").length;
    const origChars = original.length;
    const optChars = optimized.length;
    const charDiff = optChars - origChars;
    const lineDiff = optLines - origLines;
    const summary = [
      `\u{1F4CA} \u4F18\u5316\u6458\u8981`,
      `\u539F\u6587: ${origChars} \u5B57 / ${origLines} \u884C`,
      `\u4F18\u5316\u540E: ${optChars} \u5B57 / ${optLines} \u884C`,
      `\u53D8\u5316: ${charDiff >= 0 ? "+" : ""}${charDiff} \u5B57 / ${lineDiff >= 0 ? "+" : ""}${lineDiff} \u884C`
    ].join("\n");
    new import_obsidian3.Notice(summary, 5e3);
  }
};

// src/main.ts
var import_obsidian5 = require("obsidian");
var ArticleOptimizerPlugin = class extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    /**
     * 为每个提示词注册独立命令（命令面板可选）
     */
    this.registeredPromptCommandIds = [];
  }
  async onload() {
    await this.loadSettings();
    this.aiService = new AIService(this.settings);
    this.optimizer = new Optimizer(this.settings, this.aiService);
    this.statusBarItem = this.addStatusBarItem();
    this.statusBarItem.setText("\u{1F990} AI\u4F18\u5316");
    this.addCommand({
      id: "optimize-article",
      name: "\u4F18\u5316\u6587\u7AE0\uFF08\u9ED8\u8BA4\u63D0\u793A\u8BCD\uFF09",
      editorCallback: (editor, view) => {
        this.optimizer.optimize(editor, view);
      }
    });
    this.addCommand({
      id: "optimize-with-prompt",
      name: "\u4F18\u5316\u6587\u7AE0\uFF08\u9009\u62E9\u63D0\u793A\u8BCD\uFF09",
      editorCallback: (editor, view) => {
        this.showPromptSelector(editor, view);
      }
    });
    this.registerPromptCommands();
    this.addCommand({
      id: "optimize-shortcut",
      name: "\u4F18\u5316\u6587\u7AE0\uFF08\u5FEB\u6377\u952E\uFF09",
      editorCallback: (editor, view) => {
        this.optimizer.optimize(editor, view);
      }
    });
    this.addSettingTab(new OptimizerSettingTab(this.app, this));
  }
  onunload() {
  }
  async loadSettings() {
    const loaded = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, loaded);
    if (!this.settings.prompts || this.settings.prompts.length === 0) {
      this.settings.prompts = DEFAULT_SETTINGS.prompts;
    }
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.optimizer.updateSettings(this.settings);
    this.registerPromptCommands();
  }
  registerPromptCommands() {
    var _a, _b;
    for (const id of this.registeredPromptCommandIds) {
      (_b = (_a = this.app.commands) == null ? void 0 : _a.removeCommand) == null ? void 0 : _b.call(
        _a,
        `${this.manifest.id}:${id}`
      );
    }
    this.registeredPromptCommandIds = [];
    for (const prompt of this.settings.prompts) {
      const commandId = `optimize-prompt-${prompt.id}`;
      this.addCommand({
        id: commandId,
        name: `\u4F18\u5316: ${prompt.name}`,
        editorCallback: (editor, view) => {
          this.optimizer.optimize(editor, view, prompt.id);
        }
      });
      this.registeredPromptCommandIds.push(commandId);
    }
  }
  /**
   * 显示提示词选择器（命令面板风格）
   */
  showPromptSelector(editor, view) {
    const prompts = this.settings.prompts;
    if (prompts.length === 0) {
      new import_obsidian4.Notice("\u6CA1\u6709\u53EF\u7528\u7684\u63D0\u793A\u8BCD");
      return;
    }
    const modal = new PromptSuggestModal(this, prompts, (prompt) => {
      this.optimizer.optimize(editor, view, prompt.id);
    });
    modal.open();
  }
};
var PromptSuggestModal = class extends import_obsidian5.FuzzySuggestModal {
  constructor(plugin, prompts, onSelect) {
    super(plugin.app);
    this.prompts = prompts;
    this.onSelect = onSelect;
    this.setPlaceholder("\u9009\u62E9\u63D0\u793A\u8BCD...");
  }
  getItems() {
    return this.prompts;
  }
  getItemText(item) {
    return item.name;
  }
  onChooseItem(item) {
    this.onSelect(item);
  }
};
